### ISSUE TITLE
Starting in 0.9.5, these no longer show up in Style Settings, and therefore no longer work

### ISSUE THREAD

**Issue by mickmel** [mdelobelle/obsidian_supercharged_links#173]
This was the case on two computers of mine (same vault). This plugin worked great, but after updating to 0.9.5 it's not working.

The items in the "Supercharged Links" settings look the same, but "Style Settings" just says "No style settings found" and everything stays colorless.

Any ideas?

**Comment by Profile8647** [comment]
I can an confirm this is observed in a sandbox vault.

## Demo

https://user-images.githubusercontent.com/125712365/229404883-09eb0493-d2cc-43ba-8b8b-b678f80a1547.mp4

### Observed console error

```console
Uncaught (in promise) TypeError: customCss.readCssFolders is not a function
    at eval (plugin:supercharged-links-obsidian:549:23)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:supercharged-links-obsidian:31:58)
 ```

## Debug info

### Non-working version

```
SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v1.1.16
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 2
		1: Supercharged Links v0.9.5
		2: Style Settings v1.0.3
```

### Working version

```
SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v1.1.16
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 2
		1: Supercharged Links v0.9.3
		2: Style Settings v1.0.3
```

**Comment by HEmile** [comment]
Thanks for reporting. I think I accidently uploaded the wrong release... Should hopefully be fixed now.

**Comment by mickmel** [comment]
> Thanks for reporting. I think I accidently uploaded the wrong release... Should hopefully be fixed now.

Yep, it works again. Thanks for the quick update!
